version: '2'
services:
    mongo-3-2:
        container_name: "mongo-3-2"
        image: ${MONGO_IMAGE}
        volumes: 
            - ./mongo-3-2:/data/db
        ports:
            - "30022:27017"
        command: mongod --replSet rs2 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-3-3:
        container_name: "mongo-3-3"
        image: ${MONGO_IMAGE}
        volumes: 
            - ./mongo-3-3:/data/db
        ports:
            - "30033:27017"
        command: mongod --replSet rs2 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-3-1:
        container_name: "mongo-3-1"
        image: ${MONGO_IMAGE}
        volumes: 
            - ./mongo-3-1:/data/db
        ports:
            - "30031:27017"
        command: mongod --replSet rs2 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-3-2:mongo-3-2
            - mongo-3-3:mongo-3-3
        restart: always

    mongo-rs3-setup:
        container_name: "mongo-rs3-setup"
        image: ${MONGO_IMAGE}
        depends_on:
            - "mongo-3-1"
            - "mongo-3-2"
            - "mongo-3-3"
        links:
            - mongo-3-1:mongo-3-1
            - mongo-3-2:mongo-3-2
            - mongo-3-3:mongo-3-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-3-1
            - MONGO2=mongo-3-2
            - MONGO3=mongo-3-3
            - RS=rs3
        entrypoint: [ "/scripts/setup.sh" ]

        
